package com.jiyun.ipandatv.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.ipandatv.model.entity.DaoBean;
import com.jiyun.ipandatv.model.entity.DaoTopBean;

import com.jiyun.ipandatv.model.dao.DaoBeanDao;
import com.jiyun.ipandatv.model.dao.DaoTopBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoBeanDaoConfig;
    private final DaoConfig daoTopBeanDaoConfig;

    private final DaoBeanDao daoBeanDao;
    private final DaoTopBeanDao daoTopBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoBeanDaoConfig = daoConfigMap.get(DaoBeanDao.class).clone();
        daoBeanDaoConfig.initIdentityScope(type);

        daoTopBeanDaoConfig = daoConfigMap.get(DaoTopBeanDao.class).clone();
        daoTopBeanDaoConfig.initIdentityScope(type);

        daoBeanDao = new DaoBeanDao(daoBeanDaoConfig, this);
        daoTopBeanDao = new DaoTopBeanDao(daoTopBeanDaoConfig, this);

        registerDao(DaoBean.class, daoBeanDao);
        registerDao(DaoTopBean.class, daoTopBeanDao);
    }
    
    public void clear() {
        daoBeanDaoConfig.clearIdentityScope();
        daoTopBeanDaoConfig.clearIdentityScope();
    }

    public DaoBeanDao getDaoBeanDao() {
        return daoBeanDao;
    }

    public DaoTopBeanDao getDaoTopBeanDao() {
        return daoTopBeanDao;
    }

}
