package com.jiyun.ipandatv.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.ipandatv.model.db.BigImgBeanDao;

import com.jiyun.ipandatv.dao.BigImgBeanDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bigImgBeanDaoDaoConfig;

    private final BigImgBeanDaoDao bigImgBeanDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bigImgBeanDaoDaoConfig = daoConfigMap.get(BigImgBeanDaoDao.class).clone();
        bigImgBeanDaoDaoConfig.initIdentityScope(type);

        bigImgBeanDaoDao = new BigImgBeanDaoDao(bigImgBeanDaoDaoConfig, this);

        registerDao(BigImgBeanDao.class, bigImgBeanDaoDao);
    }
    
    public void clear() {
        bigImgBeanDaoDaoConfig.clearIdentityScope();
    }

    public BigImgBeanDaoDao getBigImgBeanDaoDao() {
        return bigImgBeanDaoDao;
    }

}
